
SELECT * FROM TB_FUNCIONARIO;

SELECT * FROM TB_FUNCIONARIO WHERE Salario = 5000;

SELECT * FROM TB_FUNCIONARIO WHERE Salario <> 5000;

SELECT * FROM TB_FUNCIONARIO WHERE Salario < 5000;

SELECT * FROM TB_FUNCIONARIO WHERE Salario <= 5000;

SELECT * FROM TB_FUNCIONARIO WHERE Salario >= 5000;

SELECT * FROM TB_FUNCIONARIO WHERE Salario >= 5000 AND Salario <= 9500;

SELECT * FROM TB_FUNCIONARIO WHERE Salario BETWEEN 5000 AND 9500;