SELECT NumeroPedido, COUNT(*) FROM TB_DETALHE_PEDIDO
	WHERE NumeroPedido IN(10249, 10256, 10250, 10251)
	GROUP BY NumeroPedido
	HAVING COUNT(*) <> 1

SELECT NumeroPedido, COUNT(*) FROM TB_DETALHE_PEDIDO
	GROUP BY NumeroPedido

SELECT * FROM TB_CLIENTE

INSERT INTO TB_CLIENTE(ClienteId, NomeCompleto, Contato, Cargo)
	VALUES ('OPOPO', 'MARCOS ALBERTO', 'MARIA JOAQUINA', 'VENDEDOR')

SELECT NomeCompleto, COUNT(NomeCompleto) FROM TB_CLIENTE
	GROUP BY NomeCompleto
	HAVING COUNT(NomeCompleto) > 1

SELECT * FROM TB_CLIENTE
	WHERE NomeCompleto = 'MARCOS ALBERTO'

DELETE TB_CLIENTE WHERE ClienteId = 'OPOPO'