CREATE TABLE TB_PRODUTO(
	ProdutoId INT IDENTITY(1,1),
	NumContrato INT,

	CONSTRAINT PK_PRODUTO PRIMARY KEY(ProdutoId, NumContrato)
);

CREATE TABLE TB_CLIENTE(
	CPF VARCHAR(12) NOT NULL,
	CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF)
);
